In [22]:
from sklearn.datasets import load_iris
import tensorflow as tf
import tensorflow.keras.backend as K

def tf_pca(data_tensor,PC_num=2):
    mean = tf.reduce_mean(data_tensor, axis=0, keepdims=True)
    mean_adj = data_tensor - mean #行列から平均を引いているｰ>グラム行列の期待値が分散共分散行列になる（？）
    # TODO:ちょっと曖昧なので個々の関係はまた調べること
    n_sample = tf.cast(tf.shape(data_tensor)[0]-1, tf.float32) # 不変分散で実装
    # 特異値分解をPCAに戻すときの変換，参考文献のSVDとPCAの関係を参考
    cov = tf.matmul(mean_adj, mean_adj, transpose_a=True) / n_sample # 分散共分散行列を計算して，期待値を計算
    # S:固有値^2
    # U:固有ベクトルを並べたもの=主成分ベクトル
    # V=U^T
    S, U, V = tf.linalg.svd(cov)
    # 次元削減
    U_reduce = U[:, :PC_num]
    project = tf.matmul(mean_adj, U_reduce)
    # 次元の復元
    data_rec = tf.matmul(project, U_reduce, transpose_b=True) + mean
    return U_reduce, data_rec[:5,:]

In [23]:
iris_X, iris_y = load_iris(return_X_y=True)
z = K.variable(iris_X)
U_reduce, data_rec = tf_pca(iris_X_tensor)
print("次元削減")
print(K.eval(U_reduce))
print("次元の復元")
print(K.eval(data_rec))

次元削減
[[ 0.36138654  0.6565884 ]
 [-0.08452248  0.7301618 ]
 [ 0.85667056 -0.17337231]
 [ 0.35828915 -0.0754813 ]]
次元の復元
[[5.0830393  3.5174131  1.403214   0.21353179]
 [4.7462626  3.157499   1.4635615  0.24024612]
 [4.7041197  3.1956806  1.3082168  0.17518044]
 [4.6422124  3.056966   1.4613297  0.23973244]
 [5.0717554  3.526554   1.3637383  0.19699991]]


In [24]:
iris_X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3